## SITE METADATA
## ----------------------------------------------------------------------------
site_name: Whetstone ML
site_description: A Python library to support AI/ML model validation
site_url: https://dkhundley.github.io/whetstone-ml/



## SITE CUSTOMIZATION
## ----------------------------------------------------------------------------
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - toc.integrate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode


markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - def_list
  - admonition
  - codehilite:
      guess_lang: false
  - mdx_math
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - table


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

plugins:
  - search:
      lang: en
      separator: '[\s\-]+'
  - awesome-pages: {}



## SITE NAVIGATION
## ----------------------------------------------------------------------------
docs_dir: wiki
nav:
  - Home: index.md
  - Metrics:
      - Text:
        - Overview: ./metrics/text/text_metrics.md
        - Readability Metrics: ./metrics/text/readability_metrics.md